use_default_settings: false
server:
  limiter: false
  image_proxy: false
  public_instance: false
  bind_address: "0.0.0.0"
  port: 8080
ui:
  static_use_hash: true
  default_theme: simple
  results_on_new_tab: false
  hotkeys: default
search:
  safe_search: 1
  autocomplete: "google"
  default_lang: "en"
  formats:
    - html
    - json
  default_categories:
    - general
  default_engines:
    - google
    - duckduckgo
    - bing
engines:
  - name: bing
    engine: bing
    shortcut: bi
    disabled: false
    timeout: 5.0
  - name: google
    engine: google
    shortcut: g
    disabled: false
    timeout: 5.0
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false
    timeout: 5.0
outgoing:
  request_timeout: 10.0
  max_request_timeout: 20.0
